<?php

/**
 * @file
 * Turbo pages module install hooks.
 */

/**
 * Implements hook_disable().
 */
function turbo_pages_disable() {
  unlink(PATH_TURBO_PAGES_RSS . '/turbo_pages.rss');
  rmdir(PATH_TURBO_PAGES_RSS);
  drupal_set_message(t('Directory <em>@dir</em> removed', array(
    '@dir' => PATH_TURBO_PAGES_RSS,
  )));
}

/**
 * Implements hook_uninstall().
 */
function turbo_pages_uninstall() {
  // Unset turbo_pages variables.
  variable_del('turbo_pages_rss_url');
}
